### ISSUE TITLE
archlinux无法正常登陆microsoft帐号

### ISSUE THREAD

**Issue by funny233-github** [MrShieh-X/console-minecraft-launcher#14]
系统：archlinux
图形化桌面:xorg-xinit i3(只装了这个桌面)
java：java17（pacman安装）
过程：
请在浏览器内登录您的微软账号，
如果登录成功，请返回到此处，等待完成登录。
登录需要一定的时间，请耐心等待。
Jun 14, 2022 11:45:51 PM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
java.net.SocketException: Broken pipe
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1442)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1435)
	at java.base/java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:185)
	at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:97)
	at java.base/java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:112)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.io.FileNotFoundException: cmcl.json (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:113)
	at com.mrshiehx.cmcl.utils.Utils.saveConfig(Utils.java:333)
	at com.mrshiehx.cmcl.modules.account.loginner.MicrosoftAccountLoginner.lambda$loginMicrosoftAccount$0(MicrosoftAccountLoginner.java:164)
	at com.mrshiehx.cmcl.server.MicrosoftAuthenticationServer.lambda$serve$0(MicrosoftAuthenticationServer.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
登录账号成功
 ~/CMCL1.19  sudo -u funny java -jar CMCL.jar
未选择账号。请登录了您的账号之后，使用“-account -p”列出账号，记住您要选择的账号的序号，然后使用“-account <序号>”选择账号；或者在登录账号命令后面加上“-s”的参数。
 ~/CMCL1.19  sudo -u funny java -jar CMCL.jar -p
不正确的用法。
使用选项 -usage 或 -help 以获得使用手册。
 ~/CMCL1.19  
所以如何解决这个问题，我无法登陆

**Comment by funny233-github** [comment]
解决了

**Comment by MrShieh-X** [comment]
正确的指令是`java -jar CMCL.jar -account -p`，你少打了个`-account`
