### ISSUE TITLE
启动时报错无法启动

### ISSUE THREAD

**Issue by flemon-y** [MrShieh-X/console-minecraft-launcher#36]
当我刚从CurseForge上下载好1.19.2的整合包，然后准备启动时出现以下错误

```
Starting game...
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Exception in thread "main" java.lang.ExceptionInInitializerError
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @4fccd51b
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45)
        ... 8 more
Game finished
```

**Comment by MrShieh-X** [comment]
整合包的名称是啥？cmcl版本多少？

**Comment by flemon-y** [comment]
> 整合包的名称是啥？cmcl版本多少？

整合包名：create re-flavored
CMCL版本：2.2

**Comment by MrShieh-X** [comment]
已在v2.2.1中解决
