### ISSUE TITLE
使用一段时间后登录多人服务器错误

### ISSUE THREAD

**Issue by F1Justin** [MrShieh-X/console-minecraft-launcher#37]
操作系统：macOS 14.0
登录方式：微软登录
版本：1.20.1
描述：使用一段时间后登录多人服务器提示“无法连接至服务器，登录失败：无效会话（请尝试重启游戏及启动器）”
出现该问题后，通常需要重新登录微软账号才能进入
日志：
(base) ➜  cmcl java -jar cmcl.jar 1.20.1
启动版本：1.20.1 (1.20.1) | 登录账号：F1Justin (微软账户) | Java 路径：/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java
游戏跟随启动器退出：true | 全屏：false | 最大内存：8192MB | 窗口宽：854 | 窗口高：480 | 启动前检查账号：false
游戏目录：/Users/justin/cmcl/.minecraft

启动游戏中...
[18:16:27] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 57 milliseconds
[18:16:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:16:28] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
        at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
        at enn.a(SourceFile:733) ~[1.20.1.jar:?]
        at enn.<init>(SourceFile:442) ~[1.20.1.jar:?]
        at net.minecraft.client.main.Main.main(SourceFile:211) ~[1.20.1.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
        ... 5 more
[18:16:28] [Render thread/INFO]: Setting user: F1Justin
[18:16:28] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[18:16:28] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[18:16:29] [Worker-Main-3/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
        at fes.a(SourceFile:139) ~[1.20.1.jar:?]
        at fes.b(SourceFile:79) ~[1.20.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[18:16:29] [Render thread/INFO]: Reloading ResourceManager: vanilla
[18:16:29] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[18:16:30] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:16:30] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:16:30] [Render thread/INFO]: OpenAL initialized on device CoreAudio Default
[18:16:30] [Render thread/INFO]: Sound engine started
[18:16:30] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:16:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:16:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:16:30] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:16:30] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:16:30] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:16:30] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:16:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:16:30] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:16:30] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:16:30] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:16:30] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:16:30] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:16:30] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[18:16:45] [Worker-Main-7/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
        at fes.a(SourceFile:139) ~[1.20.1.jar:?]
        at fes.b(SourceFile:79) ~[1.20.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[18:16:45] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[18:16:49] [Worker-Main-7/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
        at fes.a(SourceFile:139) ~[1.20.1.jar:?]
        at fes.b(SourceFile:79) ~[1.20.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[18:16:49] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[18:16:53] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[18:16:53] [Worker-Main-7/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
        at fes.a(SourceFile:139) ~[1.20.1.jar:?]
        at fes.b(SourceFile:79) ~[1.20.1.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
^[[C^C%

**Comment by MrShieh-X** [comment]
请通过`cmcl config checkAccountBeforeStart true`开启“启动前检查账号”功能，或者每次出现所述情况时使用`cmcl account --refresh`刷新账户后重启 Minecraft。
