### ISSUE TITLE
设置了版本隔离后无法启动包含forge的游戏

### ISSUE THREAD

**Issue by arrowdannad** [MrShieh-X/console-minecraft-launcher#39]
控制台输出

C:\Users\ARROWDANNAD>cmcl 1.19.2-养老
启动版本：1.19.2-养老 (1.19.2) | 登录账号：arrowdannad (微软账户) | Java 路径：D:\JAVA\java17\bin\java.exe
游戏跟随启动器退出：false | 全屏：false | 最大内存：4041MB | 窗口宽：854 | 窗口高：480 | 启动前检查账号：true
游戏目录：C:\Users\ARROWDANNAD\.minecraft\versions\1.19.2-养老
资源目录：C:\Users\ARROWDANNAD\.minecraft\assets
资源包目录：C:\Users\ARROWDANNAD\.minecraft\resourcepacks

启动游戏中...
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Exception in thread "main" java.lang.ExceptionInInitializerError
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @574caa3f
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45)
        ... 8 more
游戏结束

C:\Users\ARROWDANNAD>

**Comment by MrShieh-X** [comment]
你的CMCL版本是多少？可以用cmcl -a查看
你试一下用CMCL v2.2能不能启动，我有空再看下这个问题

**Comment by arrowdannad** [comment]
抱歉，在提交问题之前没有搜索相关的问题，是因为没有升级到最新版的cmcl。
是cmcl2.2发现的此问题，在cmcl2.2.1中解决了。
